services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: warehouse-sqlserver
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_DATABASE: "WarehouseDB"
    ports:
      - "1433:1433"
    networks:
      - warehouse-network
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q "SELECT 1" -b -o /dev/null
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    restart: unless-stopped

volumes:
  sqlserver-data:


networks:
  warehouse-network:
    driver: bridge
